name: blur_detector
description: Copy from Blur Detector Dart by GobalKrishnan - Perform Blur Detection using Laplacian Filter, need to set threshold to find blur or not.
version: 1.0.0
homepage: https://github.com/Crewlan/blur_detector

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.16.0
